##################################################################
# Docker Compose Configuration
#
# Description:
#       Defines multi-container services for this project.
#
# File: docker-compose.yml
# Author: Edward King Fjura
# Last Updated: 7/2/2025
#
##################################################################

services:
  db:
    image: postgres:15
    container_name: pep_postgres
    environment:
      POSTGRES_DB: pep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pepnet

  javac:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: javac_container
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    tty: true
    depends_on:
      - db
    networks:
      - pepnet

volumes:
  pgdata:

networks:
  pepnet:
