version: '3.8'

services:
  electron-builder:
    build: .
    image: electron-builder-env
    container_name: electron-builder
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
