##################################################################
#
# File: docker-build.yml
# Author: Edward King Fjura
# Last Updated: 7/2/2025
#
##################################################################

name: Build and Push to GHCR

on:
  push:
    branches: [ main ]  # or 'master' depending on your repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./JAVAC_Container
        file: ./JAVAC_Container/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/javac-container:latest